#!/usr/bin/env python3
"""Emit bench/arb_names.tsp -- the generator's waveform names, as a table the instrument can read.

    python3 tools/gen_arb_names.py            # write it
    python3 tools/gen_arb_names.py --check    # exit 1 if it is out of date

WHY GENERATED AND NOT WRITTEN BY HAND. vector_names.MAP is the one place the mapping lives, and eight of
its forty-one entries are built in a loop rather than written as literals -- so a hand copy is not merely
duplication, it is duplication that a reader cannot check by eye. A first attempt at this parsed the
Python from Lua and silently found only 29 of the 41, which is the failure mode that matters here: ARWV
NAME with a name the generator does not have does NOTHING, the previous waveform keeps playing, and the
cell is recorded against a stimulus that never appeared.

WHY A TABLE RATHER THAN A COLUMN IN THE PLAN. Both work, and the plan does still carry the name per row.
The table is what the instrument uses, because it makes the mapping inspectable on the instrument
without a plan in hand -- and the row is kept as a CROSS-CHECK, so a stale generated table cannot
quietly send the wrong name. bench_run refuses a cell whose two sources disagree instead of choosing one.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import soakplan as SP                                                    # noqa: E402
import vector_names as VN                                                # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'bench', 'arb_names.tsp')

HEAD = """-- arb_names.tsp -- GENERATED by tools/gen_arb_names.py. Do not edit; run that instead.
--
-- The generator's own name for each local vector id. C1:ARWV NAME takes a STORED WAVEFORM NAME, so
-- sending a local id like 'v77' does nothing at all and the previously selected waveform keeps playing
-- -- which would be recorded as this cell's stimulus. tools/vector_names.py is the single source, and
-- eight of these entries are generated there in a loop, so this file is emitted rather than typed.
--
-- tools/test_bench_engine.lua asserts this file is current. A vector renamed in vector_names.py without
-- regenerating here would otherwise leave the instrument playing the wrong waveform silently.

barb = barb or {}

barb.name = barb.name or {}
"""

TAIL = """
-- WHICH VECTORS ARE ALLOWED TO REFUSE. A 'loud' vector is one the plan drives into conditions where
-- declining to decode is the DOCUMENTED RIGHT ANSWER -- 20 %% jitter, a spike, a drifting clock, a LIN
-- break field -- and tools/judge_bench.py counts a refusal there as a pass. The instrument needs the
-- same list, because a status screen that shows every refusal as a failure reports about a third of a
-- healthy lap as broken: measured, 539 of 1677 cells produced no result offline and 151 of those were
-- exactly this. Anything not named here is expected to decode, so a refusal IS a failure.
--
-- GENERATED FROM tools/soakplan.py's VECTOR_EXPECT, for the same reason the names above are generated:
-- two copies of a judgement drift, and the night they disagree both look right.
barb.expect = barb.expect or {}
%s
function barb.loud(vid)
  if vid == nil then return false end
  return barb.expect[vid] == 'loud'
end

-- The count, so a truncated file is detectable rather than merely short.
barb.n = %d

-- Returns the generator's name for a vector id, or nil. Never guesses: a fallback to the id itself is
-- exactly the silent failure this table exists to prevent.
function barb.of(vid)
  if vid == nil then return nil end
  return barb.name[vid]
end
"""


def render():
    out = [HEAD]
    for vid in sorted(VN.MAP):
        out.append("barb.name['%s'] = '%s'" % (vid, VN.MAP[vid]))
    loud = ['\n'.join("barb.expect['%s'] = 'loud'" % v
                      for v in sorted(VN.MAP) if SP.expect_for(v) == 'loud')]
    out.append(TAIL % (loud[0], len(VN.MAP)))
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='exit 1 if the file is out of date')
    a = ap.parse_args()
    want = render()
    if a.check:
        have = open(OUT).read() if os.path.exists(OUT) else ''
        if have != want:
            print('STALE: %s does not match tools/vector_names.py.' % OUT)
            print('  python3 tools/gen_arb_names.py')
            return 1
        print('%s is current (%d name(s))' % (OUT, len(VN.MAP)))
        return 0
    with open(OUT, 'w') as f:
        f.write(want)
    print('wrote %s (%d name(s))' % (OUT, len(VN.MAP)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
