#!/usr/bin/env python3
"""Generate the stimulus-free repro for the launch-capture bluescreen.

WHAT MAKES THIS THE RIGHT SHAPE. One installed app demonstrates BOTH halves of the
defect, so a reader needs no second build and no version comparison:

    * it takes a digitize capture from its ENTRY POINT, which is the fault
    * it also puts a BUTTON on screen that runs the IDENTICAL capture, which is not

If the launch crashes and the button never does, the asymmetry is established inside a
single file. That is the whole claim, and it is self-contained.

NOTHING NEED BE CONNECTED. The capture is free running -- dmm.digitize.read() with no
trigger model armed -- so it fills its buffer from whatever the open input reads. Our
own application bails on a quiet line because its ANALOG TRIGGER never fires, which is
why it looked as though a signal were required; it is not, it was only doing almost no
work in that case.

TWO KNOBS, because the sufficient cause is not yet identified and the repro has to be
matched to it:

    --depth N    plain Lua call frames between the top level and the capture
    --pcalls M   pcall layers wrapping the capture

Both also let the THRESHOLD be bisected: a report that says "fails at N frames, passes
at N-1" is actionable in a way that "fails in our app" is not.

    python3 tools/repro_launchcap.py --out ~/tmp/LC.tspa --depth 2 --pcalls 1
"""
import argparse
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EOL = '\r\n'

MANIFEST = [
    ('Product', 'DMM6500, DAQ6510, DMM7510'),
    ('Tag', 'test'),
    ('Description', 'Reproduces a bluescreen: a digitize capture reached from an app '
                    'entry point, with the same capture on a button for comparison. '
                    'Nothing need be connected. Install, RESTART, then run.'),
    ('Version', '1.00'),
    ('Requires', '1.7.0'),
    ('Author', 'Ian Ameline'),
    ('License', 'MIT'),
]


def body(name, nsmp, fs, depth, pcalls, caps, nocap=False):
    o = []
    o.append('-- Generated by tools/repro_launchcap.py')
    o.append('-- depth=%d pcalls=%d nsmp=%d fs=%d' % (depth, pcalls, nsmp, fs))
    o.append('lc = {}')
    o.append('lc.nsmp, lc.fs, lc.caps = %d, %d, %d' % (nsmp, fs, caps))
    o.append('lc.ns = dmm')
    o.append('if lc.ns == nil or lc.ns.digitize == nil then lc.ns = localnode end')
    o.append('')
    # THE CAPTURE ITSELF. Free running: no trigger model is armed, so read() returns once
    # count samples are in, whatever the input is doing.
    o.append('function lc.capture()')
    if nocap:
        # NO DIGITIZER AT ALL, same call depth. If this still faults, the capture is
        # irrelevant and the defect is pcall depth on its own -- which is a far simpler
        # claim and needs no measurement subsystem to demonstrate.
        o.append('  local s, i = 0, nil')
        o.append('  for i = 1, lc.nsmp do s = s + i end')
        o.append('  lc.last = s')
        o.append('  return s')
        o.append('end')
        o.append('')
        return _finish(o, name, depth, pcalls)
    o.append('  local dig = lc.ns.digitize')
    o.append('  dig.func       = lc.ns.FUNC_DIGITIZE_VOLTAGE')
    o.append('  dig.range      = 10')
    o.append('  dig.samplerate = lc.fs')
    o.append('  dig.aperture   = 1e-6')
    o.append('  if lc.buf ~= nil then')
    o.append('    pcall(function() buffer.delete(lc.buf) end)')
    o.append('    lc.buf = nil')
    o.append('  end')
    o.append('  lc.buf = buffer.make(lc.nsmp)')
    o.append('  dig.count = lc.nsmp')
    o.append('  lc.buf.clear()')
    o.append('  dig.read(lc.buf)')
    # Read the samples out into Lua, the heaviest part of a capture.
    o.append('  local rd, t = lc.buf.readings, {}')
    o.append('  local got, i = lc.buf.n or 0, nil')
    o.append('  for i = 1, got do t[i] = rd[i] end')
    o.append('  lc.last = got')
    o.append('  return got')
    o.append('end')
    o.append('')
    # PCALL LAYERS, built as named functions rather than nested inline so the count is
    # visible in the source and cannot be miscounted by a reader.
    inner = 'lc.capture'
    for k in range(pcalls):
        fn = 'lc.p%d' % (k + 1)
        o.append('function %s()' % fn)
        o.append('  local n')
        o.append('  local ok, err = pcall(function() n = %s() end)' % inner)
        o.append('  if not ok then error(err, 0) end')
        o.append('  return n')
        o.append('end')
        inner = fn
    if pcalls:
        o.append('')
    # PLAIN CALL FRAMES, likewise named and explicit.
    for k in range(depth):
        fn = 'lc.d%d' % (k + 1)
        o.append('function %s() return %s() end' % (fn, inner))
        inner = fn
    if depth:
        o.append('')
    o.append('lc.entry = %s' % inner)
    o.append('')
    # ONE FUNCTION USED BY BOTH ROUTES, so the two differ only in what calls it.
    o.append('function lc.run(where)')
    o.append('  local i')
    o.append('  for i = 1, lc.caps do')
    o.append('    print(where .. " capture " .. i .. " of " .. lc.caps)')
    o.append('    pcall(function() display.settext(lc.txt, where .. " " .. i) end)')
    o.append('    local ok, err = pcall(function() lc.entry() end)')
    o.append('    if not ok then')
    o.append('      print("RAISED " .. tostring(err))')
    o.append('      pcall(function() display.settext(lc.txt, "raised: " .. tostring(err)) end)')
    o.append('      return false')
    o.append('    end')
    o.append('    print("  got " .. tostring(lc.last))')
    o.append('  end')
    o.append('  pcall(function() display.settext(lc.txt, where .. " DONE") end)')
    o.append('  print(where .. " DONE")')
    o.append('  return true')
    o.append('end')
    o.append('')
    o.append('function lc.from_button() lc.run("BUTTON") end')
    o.append('')
    o.append('function lc.start()')
    o.append('  lc.scr = display.create(display.ROOT, display.OBJ_SCREEN, "%s")' % name)
    o.append('  lc.txt = display.create(lc.scr, display.OBJ_TEXT, 20, 50, "ready")')
    # THE BUTTON IS CREATED BEFORE THE LAUNCH CAPTURE, so that if the launch crashes the
    # instrument the button still exists on the next run -- otherwise a reader can never
    # reach the control half of the experiment.
    # display.OBJ_BUTTON, with a WIDTH: that is the signature this firmware takes, and the
    # one the application itself uses. OBJ_BUTTON_MENU does not exist here, and a create that
    # returns nil would remove the control half of the experiment without saying so -- hence
    # the report rather than a bare pcall.
    o.append('  lc.btn = nil')
    o.append('  pcall(function()')
    o.append('    lc.btn = display.create(lc.scr, display.OBJ_BUTTON, 20, 120, "Capture", 140)')
    o.append('  end)')
    o.append('  if lc.btn == nil then')
    o.append('    print("WARNING: the button could not be created -- no control half")')
    o.append('  else')
    o.append('    pcall(function()')
    o.append('      display.setevent(lc.btn, display.EVENT_PRESS, "lc.from_button()")')
    o.append('    end)')
    o.append('  end')
    o.append('  display.changescreen(lc.scr)')
    o.append('  -- THE FAULT: the same lc.entry() the button calls, reached from the entry point.')
    o.append('  lc.run("LAUNCH")')
    o.append('end')
    o.append('')
    o.append('lc.start()')
    return EOL.join(o)


def bytecode_ok(text):
    with tempfile.NamedTemporaryFile('w', suffix='.lua', delete=False) as fh:
        fh.write(text)
        src = fh.name
    out = src + '.out'
    try:
        r = subprocess.run(['luac', '-o', out, src], capture_output=True, text=True)
        return (os.path.getsize(out), None) if r.returncode == 0 else (None, r.stderr.strip())
    finally:
        for p in (src, out):
            if os.path.exists(p):
                os.unlink(p)


def icon_tail(template, name):
    with open(template, newline='') as fh:
        text = fh.read()
    tail = text[text.index('\r\nendscript'):]
    return re.sub(r'loadimage sdec_icon \S+', 'loadimage sdec_icon ' + name, tail)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    ap.add_argument('--name', default=None)
    ap.add_argument('--depth', type=int, default=2, help='plain call frames before the capture')
    ap.add_argument('--pcalls', type=int, default=1, help='pcall layers around the capture')
    ap.add_argument('--nsmp', type=int, default=20000)
    ap.add_argument('--fs', type=int, default=1000000)
    ap.add_argument('--caps', type=int, default=3, help='captures per run')
    ap.add_argument('--no-capture', action='store_true',
                    help='same depth, but no digitizer: tests pcall depth alone')
    ap.add_argument('--template', default=os.path.join(ROOT, 'Serial_Decode.tspa'),
                    help='archive to borrow a known-good icon block from')
    a = ap.parse_args()
    name = a.name or re.sub(r'[^A-Za-z0-9_]', '',
                            os.path.basename(a.out).rsplit('.', 1)[0]).upper()

    text = body(name, a.nsmp, a.fs, a.depth, a.pcalls, a.caps, a.no_capture)
    bc, err = bytecode_ok(text)
    if bc is None:
        raise SystemExit('generated body does not compile: %s' % err)

    out = ['loadscript ' + name, '-- $Title: ' + name]
    for k, v in MANIFEST:
        out.append('-- $%s: %s' % (k, v))
    out.append('-- $Icon: sdec_icon')
    out.append('')
    archive = EOL.join(out) + EOL + text + icon_tail(a.template, name)
    with open(a.out, 'w', newline='') as fh:
        fh.write(archive)
    print('wrote %s' % a.out)
    print('  script/title  %s' % name)
    print('  depth %d plain frames, %d pcall layers' % (a.depth, a.pcalls))
    print('  %d samples at %d S/s, %d captures per run' % (a.nsmp, a.fs, a.caps))
    print('  body %d bytes, bytecode %d bytes, archive %d bytes'
          % (len(text), bc, len(archive)))


if __name__ == '__main__':
    main()
