#!/usr/bin/env python3
"""Generate a standalone TSP app of a chosen compiled size, for a vendor repro.

THE DEFECT. On a DMM6500 (1.7.17a) a TSP app installed into internal memory runs
correctly when freshly installed, and bluescreens the instrument after the next restart.
The same archive run from a USB key never fails, and the installed app's stored source
is byte-identical to the working copy. Bisecting this project's own releases put a
boundary between a build with ~180.6 kB of compiled chunk (works) and ~186.6 kB
(crashes), with stored source 260 kB and 270 kB respectively.

WHY THIS EXISTS RATHER THAN A POINTER AT OUR APP. Our app needs a serial signal on the
input to reach the crash, which means anybody reproducing it needs a second instrument
and a wired-up vector. That is the single biggest reason a report gets closed unread. A
generated app needs nothing attached: no signal, no digitizer, no USB key, no second
instrument. It only has to be BIG, and to RUN.

PADDING THAT EXECUTES, WHICH IS THE OPPOSITE OF probe_appsize.py. That tool wraps its
padding in `if false then` so a bigger build is not also a build that does more work --
correct when isolating size. Here the padding is CALLED, because the hypothesis under
test is a damaged cached compile, and a fault in a compiled image appears when execution
reaches it. An app that is large but never executes its bulk would not provoke it.

PROGRESS IS REPORTED AS IT GOES, so a crash localises itself: the last number on the
panel says how far execution got before the instrument died. That turns "it bluescreens"
into "it bluescreens after N of M blocks", which is a far better bug report.

    python3 tools/repro_bigapp.py --bytecode 190000 --out ~/tmp/BIGTEST.tspa
    python3 tools/push_tspa.py --file ~/tmp/BIGTEST.tspa --dest /usb1/BIGTEST.tspa

Then install it from Manage Apps, restart the instrument, and run it.
"""
import argparse
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EOL = '\r\n'

# THE SCRIPT NAME IS PER-BUILD, NOT A CONSTANT, and that is not cosmetic. Two archives
# declaring the same `loadscript` name install as two internal apps that the front panel
# lists identically, and then nobody can say which one a test actually ran. That has
# already cost one round of results here. Derived from --out so it cannot drift from the
# filename, and overridable with --name.
MANIFEST = [
    ('Product', 'DMM6500, DAQ6510, DMM7510'),
    ('Tag', 'test'),
    ('Description', 'Size-parameterised app for reproducing a firmware fault. '
                    'Needs nothing connected: no signal, no USB key, no digitizer. '
                    'Install it, RESTART the instrument, then run it.'),
    ('Version', '1.00'),
    ('Requires', '1.7.0'),
    ('Author', 'Ian Ameline'),
    ('License', 'MIT'),
]

# ONE BLOCK OF WORK, repeated. Each is a real function doing real arithmetic on a local
# table, so it compiles to a comparable amount of chunk every time and the padding count
# maps predictably onto bytecode. Nothing here touches the instrument.
BLOCK = """function rb.f%(i)06d(x)
  local t = {}
  local j
  for j = 1, 8 do t[j] = (x + j) * %(i)d end
  local s = 0
  for j = 1, 8 do s = s + t[j] end
  if s > 1e9 then s = s - 1e9 end
  return s
end"""


def body(name, nblocks, execute, report_every, work=0, work_passes=4):
    out = []
    out.append('-- Generated by tools/repro_bigapp.py. %d blocks.' % nblocks)
    out.append('rb = {}')
    out.append('rb.n = %d' % nblocks)
    for i in range(nblocks):
        out.extend((BLOCK % {'i': i}).split('\n'))
    out.append('')
    out.append('function rb.run()')
    out.append('  local s = 0')
    if execute:
        # CALLED THROUGH THE TABLE so the compiler cannot fold the calls away, and in
        # index order so the "got to block N" report is monotonic and means something.
        out.append('  local i')
        out.append('  for i = 0, rb.n - 1 do')
        out.append('    local f = rb["f" .. string.format("%06d", i)]')
        out.append('    if f ~= nil then s = s + f(i) end')
        out.append('    if math.mod(i, %d) == 0 then' % report_every)
        out.append('      rb.mark = i')
        out.append('      print("BLOCK " .. i .. " of " .. rb.n)')
        out.append('    end')
        out.append('  end')
    out.append('  return s')
    out.append('end')
    out.append('')
    # A SCREEN, because an app the operator cannot see has not been launched as far as
    # they are concerned, and because this is how our real app looks to the firmware.
    # A DECODE-SHAPED WORKLOAD, WITH NOTHING ATTACHED. Calling many small functions is not
    # what the real app does when it crashes: a capture that decodes allocates a sample array
    # of tens of thousands of numbers, a table per frame, and strings for the dump rows, and a
    # capture of a QUIET pin -- which allocates almost none of that -- has never crashed. So
    # size alone was never going to reproduce it; this is the part that was missing.
    #
    # SYNTHESISED, NOT MEASURED: the samples are generated arithmetically, so this needs no
    # signal, no generator and no digitizer, which is the whole point of the exercise.
    out.append('function rb.work(nsmp)')
    out.append('  local smp = {}')
    out.append('  local i')
    out.append('  for i = 1, nsmp do')
    out.append('    smp[i] = math.mod(i * 37, 211) - 105')
    out.append('  end')
    out.append('  -- frame-shaped: a table per group, as the decoder builds per byte')
    out.append('  local frames, nf = {}, 0')
    out.append('  for i = 1, nsmp - 10, 10 do')
    out.append('    nf = nf + 1')
    out.append('    frames[nf] = {v = smp[i], e = nil, t = i}')
    out.append('  end')
    out.append('  -- dump rows, as the panel builds them')
    out.append('  local rows, nr = {}, 0')
    out.append('  for i = 1, nf, 16 do')
    out.append('    local parts, np = {}, 0')
    out.append('    local j')
    out.append('    for j = i, i + 15 do')
    out.append('      if frames[j] ~= nil then')
    out.append('        np = np + 1')
    out.append('        parts[np] = string.format("%02X", math.mod(frames[j].v + 256, 256))')
    out.append('      end')
    out.append('    end')
    out.append('    nr = nr + 1')
    out.append('    rows[nr] = table.concat(parts, " ")')
    out.append('  end')
    out.append('  rb.nf, rb.nr = nf, nr')
    out.append('  return nf + nr')
    out.append('end')
    out.append('')
    out.append('function rb.start()')
    out.append('  local scr = display.create(display.ROOT, display.OBJ_SCREEN, "%s")' % name)
    out.append('  rb.scr = scr')
    out.append('  rb.txt = display.create(scr, display.OBJ_TEXT, 20, 60, "running...")')
    out.append('  display.changescreen(scr)')
    out.append('  local ok, err = pcall(function() rb.sum = rb.run() end)')
    if work:
        # RUN AFTER the block sweep, and REPEATEDLY: one decode-sized allocation may be
        # absorbed, where the real app does one per capture and crashes on a later one.
        out.append('  if ok then')
        out.append('    local k')
        out.append('    for k = 1, %d do' % work_passes)
        out.append('      pcall(function() display.settext(rb.txt, "work pass " .. k) end)')
        out.append('      print("WORK pass " .. k)')
        out.append('      ok, err = pcall(function() rb.sum = rb.sum + rb.work(%d) end)' % work)
        out.append('      if not ok then break end')
        out.append('      pcall(function() collectgarbage() end)')
        out.append('    end')
        out.append('  end')
    out.append('  local msg')
    out.append('  if ok then msg = "done, " .. rb.n .. " blocks, sum " .. tostring(rb.sum)')
    out.append('  else msg = "raised at block " .. tostring(rb.mark) .. ": " .. tostring(err) end')
    out.append('  pcall(function() display.settext(rb.txt, msg) end)')
    out.append('  print(msg)')
    out.append('end')
    out.append('')
    out.append('rb.start()')
    return EOL.join(out)


def bytecode_size(text):
    with tempfile.NamedTemporaryFile('w', suffix='.lua', delete=False) as fh:
        fh.write(text)
        src = fh.name
    out = src + '.out'
    try:
        r = subprocess.run(['luac', '-o', out, src], capture_output=True, text=True)
        if r.returncode != 0:
            return None, r.stderr.strip()
        return os.path.getsize(out), None
    finally:
        for p in (src, out):
            if os.path.exists(p):
                os.unlink(p)


def icon_tail(template, name):
    """The icon block from an existing archive, rebound to this script's name.

    REUSED RATHER THAN OMITTED: a .tspa with no $Icon/loadimage may or may not satisfy
    this firmware's installer, and finding out costs a trip to the instrument. Borrowing
    a known-good icon block removes the question from the experiment.
    """
    with open(template, newline='') as fh:
        text = fh.read()
    i = text.index('\r\nendscript')
    tail = text[i:]
    for old in ('Serial_Decode', 'SERIAL_TEST'):
        tail = tail.replace('loadimage sdec_icon ' + old, 'loadimage sdec_icon ' + name)
    return tail


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    ap.add_argument('--bytecode', type=int, required=True,
                    help='target compiled size in bytes, e.g. 190000')
    ap.add_argument('--no-exec', action='store_true',
                    help='generate the bulk but never call it (size-only control)')
    ap.add_argument('--name', default=None,
                    help='script name and title; defaults to the --out basename, upper-cased')
    ap.add_argument('--work', type=int, default=0,
                    help='samples per decode-shaped pass; 0 disables the workload')
    ap.add_argument('--work-passes', type=int, default=4)
    ap.add_argument('--report-every', type=int, default=200)
    ap.add_argument('--template', default=os.path.join(ROOT, 'Serial_Decode.tspa'),
                    help='archive to borrow a known-good icon block from')
    a = ap.parse_args()
    execute = not a.no_exec
    name = a.name or re.sub(r'[^A-Za-z0-9_]', '',
                            os.path.basename(a.out).rsplit('.', 1)[0]).upper()
    if not name:
        raise SystemExit('could not derive a script name from --out; pass --name')

    lo, hi = 1, 64
    while True:
        bc, err = bytecode_size(body(name, hi, execute, a.report_every, a.work, a.work_passes))
        if bc is None:
            raise SystemExit('generated body does not compile: %s' % err)
        if bc >= a.bytecode:
            break
        hi *= 2
        if hi > 400000:
            raise SystemExit('cannot reach %d' % a.bytecode)
    while lo < hi:
        mid = (lo + hi) // 2
        bc, _ = bytecode_size(body(name, mid, execute, a.report_every, a.work, a.work_passes))
        if bc is None or bc < a.bytecode:
            lo = mid + 1
        else:
            hi = mid
    nblocks = lo

    text = body(name, nblocks, execute, a.report_every, a.work, a.work_passes)
    bc, err = bytecode_size(text)
    if bc is None:
        raise SystemExit('final body does not compile: %s' % err)

    out = ['loadscript ' + name]
    out.append('-- $Title: ' + name)
    for k, v in MANIFEST:
        out.append('-- $%s: %s' % (k, v))
    out.append('-- $Icon: sdec_icon')
    out.append('')
    archive = EOL.join(out) + EOL + text + icon_tail(a.template, name)
    with open(a.out, 'w', newline='') as fh:
        fh.write(archive)

    print('wrote %s' % a.out)
    print('  script name / title: %s' % name)
    print('  work: %s'
          % ('%d samples x %d passes' % (a.work, a.work_passes) if a.work else 'none'))
    print('  %d blocks, %s' % (nblocks, 'EXECUTED at startup' if execute else 'never called'))
    print('  body     %d bytes' % len(text))
    print('  bytecode %d bytes (target %d)' % (bc, a.bytecode))
    print('  archive  %d bytes' % len(archive))


if __name__ == '__main__':
    main()
